// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_StatusBar;
lv_obj_t * ui_SignalStrength;
lv_obj_t * ui_JoyImage;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_add_state(ui_MainScreen, LV_STATE_PRESSED);       /// States
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatusBar = lv_label_create(ui_MainScreen);
    lv_obj_set_height(ui_StatusBar, 13);
    lv_obj_set_width(ui_StatusBar, lv_pct(100));
    lv_obj_set_x(ui_StatusBar, 0);
    lv_obj_set_y(ui_StatusBar, 31);
    lv_obj_set_align(ui_StatusBar, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_StatusBar, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_StatusBar, "STATUS");
    lv_label_set_recolor(ui_StatusBar, "true");
    lv_obj_set_style_text_align(ui_StatusBar, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatusBar, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SignalStrength = lv_bar_create(ui_MainScreen);
    lv_bar_set_value(ui_SignalStrength, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui_SignalStrength, 4);
    lv_obj_set_height(ui_SignalStrength, 51);
    lv_obj_set_x(ui_SignalStrength, 73);
    lv_obj_set_y(ui_SignalStrength, -10);
    lv_obj_set_align(ui_SignalStrength, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SignalStrength, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    ui_JoyImage = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_JoyImage, &ui_img_joy_normal_png);
    lv_obj_set_width(ui_JoyImage, 48);
    lv_obj_set_height(ui_JoyImage, 48);
    lv_obj_set_x(ui_JoyImage, 40);
    lv_obj_set_y(ui_JoyImage, -9);
    lv_obj_set_align(ui_JoyImage, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_JoyImage, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

}

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
