// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_events.h"
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_StatusBar;
extern lv_obj_t * ui_SignalStrength;
extern lv_obj_t * ui_JoyImage;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_joy_normal_png);    // assets/joy_normal.png
LV_IMG_DECLARE(ui_img_settings_white_png);    // assets/settings_white.png
LV_IMG_DECLARE(ui_img_joy_rt_png);    // assets/joy_rt.png
LV_IMG_DECLARE(ui_img_joy_lf_png);    // assets/joy_lf.png
LV_IMG_DECLARE(ui_img_joy_dn_png);    // assets/joy_dn.png
LV_IMG_DECLARE(ui_img_joy_up_png);    // assets/joy_up.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
